apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: lstack-system
data:
  config.yaml: |
    rules:
    - seriesQuery: '{__name__=~"istio_requests_total"}'
      seriesFilters: []
      resources:
        overrides:
          kubernetes_namespace:
            resource: namespace
          kubernetes_pod_name:
            resource: pod
          destination_canonical_service:
            resource: service
      name:
        matches: "^(.*)_total"
        as: "${1}_per_min"
      metricsQuery: sum(increase(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)


